version: '3.8'

services:
  # Headless mode (default) - for server environments
  automail-headless:
    build:
      context: .
      network: host
    container_name: automail-agent-headless
    network_mode: host
    volumes:
      # Data persistence (basic mounts, browsers will be added by setup script)
      - ./logs:/home/app/logs
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - BROWSER_HEADLESS=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Development mode with live reload
  automail-dev:
    build:
      context: .
      target: development
      network: host
    network_mode: host
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
      - DISPLAY=${DISPLAY:-:0}
    command: python main.py --reload
    restart: unless-stopped
    profiles:
      - dev 